# main menu
[[main]]
name = "Inici"
url = "/"
weight = 1

[[main]]
name = "Sobre mi"
url = "/about"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contacte"
url = "/contact"
weight = 5

# footer menu middle (Recursos)
[[footer_middle]]
name = "Blog"
url = "/blog"

[[footer_middle]]
name = "Sobre mi"
url = "/about"

# footer menu right (Legal)
[[footer_right]]
name = "Avís Legal"
url = "/aviso-legal"

[[footer_right]]
name = "Política de Cookies"
url = "/cookie-policy"

