# main menu
[[main]]
name = "Inici"
url = "/"
weight = 1

[[main]]
name = "Sobre mi"
url = "/about"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contacte"
url = "/contact"
weight = 5

# footer menu left (Serveis)
[[footer_left]]
name = "Coaching Executiu"
url = "/#services"

[[footer_left]]
name = "Coaching Personal"
url = "/#services"

[[footer_left]]
name = "PMaaS & CMaaS"
url = "/#services"

[[footer_left]]
name = "Consultoria del Canvi"
url = "/#services"

# footer menu middle (Recursos)
[[footer_middle]]
name = "Blog"
url = "/blog"

[[footer_middle]]
name = "Sobre mi"
url = "/about"

# footer menu right (Legal)
[[footer_right]]
name = "Política de privacitat"
url = "/privacy-policy"

[[footer_right]]
name = "Termes i condicions"
url = "/terms-conditions"
