# main menu
[[main]]
name = "Home"
url = "/en/"
weight = 1

[[main]]
name = "About Me"
url = "/en/about"
weight = 3

[[main]]
name = "Blog"
url = "/en/blog"
weight = 4

[[main]]
name = "Contact"
url = "/en/contact"
weight = 5

# footer menu middle (Resources)
[[footer_middle]]
name = "Blog"
url = "/en/blog"

[[footer_middle]]
name = "About Me"
url = "/en/about"

# footer menu right (Legal)
[[footer_right]]
name = "Legal Notice"
url = "/en/aviso-legal"

[[footer_right]]
name = "Cookie Policy"
url = "/en/cookie-policy"

