# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Acerca de mí"
url = "/about/"
weight = 3

[[main]]
name = "Blog"
url = "/blog/"
weight = 4

[[main]]
name = "Contacto"
url = "/contact/"
weight = 5

# footer menu middle (Recursos)
[[footer_middle]]
name = "Blog"
url = "/blog/"

[[footer_middle]]
name = "Acerca de mí"
url = "/about/"

[[footer_middle]]
name = "Contacto"
url = "/contact/"

# footer menu right (Legal)
[[footer_right]]
name = "Aviso Legal"
url = "/aviso-legal/"

[[footer_right]]
name = "Política de Cookies"
url = "/cookie-policy/"
