# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "/about"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5

# footer menu middle (Ressources)
[[footer_middle]]
name = "Blog"
url = "/blog"

[[footer_middle]]
name = "À propos"
url = "/about"

# footer menu right (Légal)
[[footer_right]]
name = "Mentions Légales"
url = "/aviso-legal"

[[footer_right]]
name = "Politique de Cookies"
url = "/cookie-policy"

