# main menu
[[main]]
name = "Inici"
url = "/ca/"
weight = 1

[[main]]
name = "Sobre mi"
url = "/ca/about/"
weight = 3

[[main]]
name = "Blog"
url = "/ca/blog/"
weight = 4

[[main]]
name = "Contacte"
url = "/ca/contact/"
weight = 5

# footer menu middle (Recursos)
[[footer_middle]]
name = "Blog"
url = "/ca/blog/"

[[footer_middle]]
name = "Sobre mi"
url = "/ca/about/"

[[footer_middle]]
name = "Contacte"
url = "/ca/contact/"

# footer menu right (Legal)
[[footer_right]]
name = "Avís Legal"
url = "/ca/aviso-legal/"

[[footer_right]]
name = "Política de Cookies"
url = "/ca/cookie-policy/"

[[footer_right]]
name = "Política de Privacitat"
url = "/ca/privacy-policy/"

[[footer_right]]
name = "Termes i Condicions"
url = "/ca/terms-conditions/"
