# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5

# footer menu middle (Resources)
[[footer_middle]]
name = "Blog"
url = "/blog"

[[footer_middle]]
name = "About"
url = "/about"

# footer menu right (Legal)
[[footer_right]]
name = "Legal Notice"
url = "/aviso-legal"

[[footer_right]]
name = "Cookie Policy"
url = "/cookie-policy"

